name: http_plus
description: >-
  package:http compatible client that can speak HTTP/2, maintain connections and fallback to HTTP/1.1.
version: 0.1.4
homepage: https://github.com/daadu/http_plus

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  http: ^0.13.0
  http2: ^2.0.0
  http_parser: ^4.0.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
